name: Analysis

on: push

jobs:

  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Set up uv
        uses: astral-sh/setup-uv@v6
      - name: Set up the project
        run: uv sync --locked --dev
      - name: Static analysis using Pylint
        run: uv run pylint --exit-zero --score=y -- skytracker

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Set up uv
        uses: astral-sh/setup-uv@v6
      - name: Set up the project
        run: uv sync --locked --dev
      - name: Unit test using Pytest
        run: uv run pytest
